version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: meu-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: empresa
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: meu-redis
    ports:
      - "6379:6379"
